Feature/104 implement sql alchemy
communitiesuk/funding-service-design-post-award-data-store pull request #12
Opened 2023-04-26 15:19 UTC by bobbi-hbrown

https://trello.com/c/xo7Uvx3E/104-replace-fake-datastore-with-sqlite-sqlalchemy

### Change description
This PR adds an in-memory SQLite datastore alongside the mock DB so we can start building our models on top of it.

- [ X] Unit tests and other appropriate tests added or updated
- [ X] README and other documentation has been updated / added (if needed)
- [X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### Screenshots of UI changes (if applicable)

2023-04-27 07:14 UTC, cyrusdobbs commented on core/db/db_models/contact.py
I don't think we should split models into separate files like this. A file per model is just the same problem but at the file level - which IMO is worse and doesn't actually help organisation. I also don't see any obvious logical groups to put them in. I think illogical or unobvious groupings would be worse than one module full of models too.

Keen to hear what others think too though?

2023-04-27 07:24 UTC, cyrusdobbs commented on tests/conftest.py
> +        yield
I think we want to add this after `yield` to wipe the DB after each test.

```
db.session.remove()
db.drop_all()
```

2023-04-27 14:12 UTC, nsnape requested changes

2023-04-27 15:29 UTC, bobbi-hbrown commented on core/db/db_models/contact.py
> +class Contact(db.Model):
Sounds good, we can start adding these now as we build out the models

2023-04-28 10:11 UTC, nsnape approved these changes

2023-04-28 10:11 UTC, merged