[BAU] database nullability fix for round 1
communitiesuk/funding-service-design-post-award-data-store pull request #124
Opened 2023-06-14 14:57 UTC by Joel-Pearce

A small database change in order to successfully ingest Round 1 rows where values are typically null for given columns.

These are:
- Project.location_multiplicity 
- ProjectProgress.adjustment_request_status
- ProjectProgress.start_date
- ProjectProgress.end_date

- [ ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

2023-06-14 15:06 UTC, nsnape requested changes
Yeah, all looks good since those changed fields will be caught by validation in R3. 

We can just leave this PR open until the migrations is fixed, so I guess rebase into your ingest file for now, to test?

2023-06-19 09:05 UTC, nsnape requested changes

2023-06-19 09:14 UTC, Joel-Pearce commented on db/migrations/versions/2023_06_16_1012-3c57bc0427b8_.py
> +Revision ID: 3c57bc0427b8
I've changed the name of the migration file to correspond to the above naming convention. Will rename to this format in future.

2023-06-19 15:42 UTC, nsnape requested changes

2023-06-19 15:42 UTC, nsnape commented on db/migrations/versions/004_alter_field_nullabilities_for_round_1_data.py
> +Revision ID: 3c57bc0427b8
just checking, is this id still right? Did you re-generate the migration or just change the name of the existing one? 

I think this line needs to reflect the file name, but the old auto-generated ones here don't seem to account for the date prefix so just checking it's not still using that hash id.

2023-06-19 16:01 UTC, merged