[SMD-168] extract and transform Round 4
communitiesuk/funding-service-design-post-award-data-store pull request #254
Opened 2023-09-20 14:31 UTC by cyrusdobbs

https://dluhcdigital.atlassian.net/browse/SMD-168

### Change description
- creates a new "ETL pipeline" for Round 4. 
- this uses much of the existing functionality from Round 3 with the exception of changes to the Programme Progress tab
- Round 4 includes two new columns to the Project Progress table
- Round 4 removes Programme Progress Question 6 from needing to be ingested

- [X] Unit tests and other appropriate tests added or updated
- [X] README and other documentation has been updated / added (if needed)
- [X] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### Screenshots of UI changes (if applicable)

2023-09-20 16:00 UTC, Connor-OS reviewed
Looks very good

2023-09-21 07:52 UTC, nsnape commented on core/controllers/ingest.py
>      "tf_round_three": ingest_towns_fund_data,
we could potentially rename ingest_towns_fund_data to mention round 3, so it matches the other extraction function naming conventions?

2023-09-21 07:57 UTC, cyrusdobbs commented on core/controllers/ingest.py
>      "tf_round_three": ingest_towns_fund_data,
I agree, it makes sense to rename

2023-09-21 07:59 UTC, nsnape commented on core/extraction/towns_fund_round_four.py
> +import pandas as pd
could we add a docstring at module level, which mentions what Round 4 is? ie that it's Towns Fund data and the reporting dates? We could also add one for the other Reporting round extraction modules?

2023-09-21 10:07 UTC, nsnape requested changes

2023-09-21 10:07 UTC, nsnape commented on core/extraction/towns_fund_round_three.py
> +Methods specifically for extracting data from Towns Fund Round 4 reporting template used for Reporting Round
Should say round 3

2023-09-21 10:56 UTC, nsnape approved these changes

2023-09-21 10:56 UTC, merged