[FMD-106] Write dates as Excel 'dates' not strings
communitiesuk/funding-service-design-post-award-data-store pull request #357
Opened 2023-11-09 14:50 UTC by mattpep

### Change description
Extract date fields (e.g. StartDate, EndDate on Funding) to be Excel dates not strings

- [x] Unit tests and other appropriate tests added or updated
- [ ] README and other documentation has been updated / added (if needed)
- [x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### Screenshots of UI changes (if applicable)

2023-11-15 09:10 UTC, mattpep commented on core/serialisation/data_serialiser.py
> +    end_date = fields.Raw(data_key="EndDate")
Added some tests in tests/serialisation_tests/test_serialisation.py

2023-11-15 09:11 UTC, mattpep commented on core/controllers/download.py
> +    return obj
Added test to tests/controller_tests/test_download.py

2023-11-15 09:58 UTC, mattpep commented on core/serialisation/data_serialiser.py
> +    start_date = fields.Raw(data_key="StartDate")
Additional fields now converted too.

2023-11-15 10:33 UTC, mattpep commented on core/controllers/download.py
> +def date_to_string(obj) -> str:
An exception is now raised for unhandled types (it's a different one because the error gets swallowed by the default handler)

2023-11-15 20:31 UTC, nsnape requested changes

2023-11-15 20:31 UTC, nsnape commented on core/serialisation/data_serialiser.py
> +    start_date = fields.Raw(data_key="StartDate")
There is still a field left not converted: `ProjectProgress` -> `date_of_important_milestone` is still a raw string rather than a datetime.

2023-11-16 09:48 UTC, nsnape approved these changes

2023-11-16 09:54 UTC, merged