BAU: testing for parse auth
communitiesuk/funding-service-design-post-award-data-store pull request #380
Opened 2023-11-27 11:49 UTC by Joel-Pearce

Add tests for the method ```parse_auth```.

- [ ] Unit tests and other appropriate tests added or updated
- [ ] README and other documentation has been updated / added (if needed)
- [ ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

2023-11-27 12:37 UTC, cyrusdobbs requested changes

2023-11-27 13:54 UTC, Joel-Pearce commented on tests/controller_tests/test_ingest.py
> +    assert caplog.messages[0] == "Invalid auth JSON"
I've updated this to raise the error rather than return a code. Or is it better we raise a 400?

2023-11-30 08:39 UTC, cyrusdobbs reviewed
looks good 👍

2023-11-30 08:39 UTC, cyrusdobbs commented on tests/integration_tests/test_ingest_component.py
> +    )
It's not clear exactly what causes the 400 here. Could it be made explicit

2023-11-30 14:57 UTC, cyrusdobbs approved these changes
LGTM 👍

2023-11-30 15:40 UTC, merged