[#PAB-342] implement the new data model changes
communitiesuk/funding-service-design-post-award-data-store pull request #44
Opened 2023-05-24 15:46 UTC by cyrusdobbs

https://trello.com/c/HIYrpcys/342-goal-data-model-changes-implementation

### Change description
Implemented the new data model changes to the entities. 

- [x] Unit tests and other appropriate tests added or updated
- [NA] README and other documentation has been updated / added (if needed)
- [X] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### Screenshots of UI changes (if applicable)

2023-05-24 15:48 UTC, cyrusdobbs commented
First draft done

TODO:

- Add submission table
- Implement `populate_db` changes
- Test ingest of the data model spreadsheet

2023-05-25 14:16 UTC, nsnape requested changes

2023-05-25 21:28 UTC, nsnape commented on core/db/entities.py
> +    # TODO: configured as an array of strings. is this ok? can we / should we validate for this?
Yeah let's leave it in and try it out

2023-05-25 21:28 UTC, nsnape commented on core/db/entities.py
> +    # TODO: does this unique index look right?
Yeah I think this will be fine

2023-05-26 11:02 UTC, nsnape requested changes
Great stuff, sorry about the inundation of comments, there will be a bit of an iterative review process for this I think :)

2023-05-26 11:02 UTC, nsnape commented on core/db/entities.py
> +    # TODO: add logic to support nullable but one of programme or project id requred
in this case, that will be added to the __table_args__ tuple that we already use to define the unique index.

2023-05-26 12:29 UTC, nsnape requested changes

2023-05-26 12:29 UTC, nsnape commented on core/db/entities.py
> +    locations = sqla.Column(sqla.ARRAY(sqla.String), nullable=False)
also, can we please add a field to capture the "Are you providing a GIS map (see guidance) with your return?" column. Should be nullable and a yes/no enum.

2023-05-30 08:11 UTC, cyrusdobbs commented on core/db/entities.py
> +    spend_for_reporting_period = sqla.Column(sqla.Float(), nullable=True)
I've also changed spend_before_reporting_commenced to nullable with default 0

2023-05-30 08:12 UTC, cyrusdobbs commented on core/db/entities.py
> +    spend_for_reporting_period = sqla.Column(sqla.Float(), nullable=True)
and spend_beyond_fund_lifetime

2023-05-31 09:35 UTC, nsnape requested changes

2023-05-31 09:35 UTC, nsnape commented on core/db/entities.py
> +    # TODO: add logic to support nullable but one of programme or project id requred
oh, no actually it needs to be XOR, one OR the other but not both

2023-05-31 10:12 UTC, nsnape requested changes

2023-05-31 14:45 UTC, nsnape requested changes

2023-05-31 14:45 UTC, nsnape commented on core/db/entities.py
> +
can you add "additional_information" nullable string field to OutputData?

2023-05-31 14:45 UTC, nsnape commented on core/db/entities.py
we also need to add a new field to this one: "higher_frequency", nullable string

2023-05-31 15:38 UTC, nsnape commented on core/db/entities.py
> +    # locations = sqla.Column(sqla.ARRAY(sqla.String), nullable=False)  # ARRAY not supported by SQLite
thinking about it, let's not use the array at all - that reply's far to much on users entering in some valid format. Just a string is fine (can remove the comment).

2023-06-01 10:11 UTC, merged